# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SickBoys' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SickBoys
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'SwiftyJSON'

  target 'SickBoysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SickBoysUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
